ortoreal/clients/urls.py
from django.urls import include, path

from clients import views

app_name = "clients"

urlpatterns = [
    path("", views.ClientsListView.as_view(), name="index"),
    path("contacts/", views.contacts, name="contacts"),
    path("contacts/add/", views.add_contact, name="add_contact"),
    path("contacts/edit/<int:pk>", views.edit_contact, name="edit_contact"),
    path("clients/", views.ClientsListView.as_view(), name="clients"),
    path("jobs/<int:pk>/", views.JobDetailView.as_view(), name="job"),
    path("job/add/", views.JobCreateView.as_view(), name="add_job"),
    # path("jobs/all/", views.AllClientsListView.as_view(), name="all_jobs"),
    path("clients/<int:pk>/", views.ClientView.as_view(), name="client"),
    path(
        "clients/<int:pk>/add_job/",
        views.JobCreateView.as_view(),
        name="add_job_client",
    ),
    path(
        "clients/<int:pk>/add_contact/",
        views.ContactCreateView.as_view(),
        name="add_contact",
    ),
    path(
        "clients/add/",
        views.ClientCreateView.as_view(),
        name="add_client",
    ),
    path(
        "jobs/<int:pk>/status/",
        views.JobChangeStatusView.as_view(),
        name="change_job_status",
    ),
    path(
        "jobs/<int:pk>/status/<int:status_pk>/",
        views.JobChangeStatusView.as_view(),
        name="edit_job_status",
    ),
]

ortoreal/inventory/urls.py
from django.urls import path

from inventory import views

app_name = "inventory"

urlpatterns = [
    path(
        "nomenclature/",
        views.NomenclatureListView.as_view(),
        name="nomenclature",
    ),
    path("items/<int:pk>/", views.PartItemsListView.as_view(), name="items"),
    path("reception/", views.ReceptionView.as_view(), name="reception"),
    path(
        "reception/<int:pk>/",
        views.ReceptionInvoiceView.as_view(),
        name="reception_invoice",
    ),
    path("take/", views.TakeItemsView.as_view(), name="take_items"),
    path("return/", views.ReturnItemsView.as_view(), name="return_items"),
    path("add_parts/", views.AddPartsView.as_view(), name="add_parts"),
    path("orders/", views.OrdersView.as_view(), name="orders"),
    path(
        "vendor_orders/",
        views.VendorOrdersView.as_view(),
        name="vendor_orders",
    ),
    path("orders/current/", views.OrderView.as_view(), name="order"),
    path(
        "orders/current/edit/",
        views.FreeOrderEditView.as_view(),
        name="free_order_edit",
    ),
    path("orders/<int:pk>/", views.OrderView.as_view(), name="order_by_id"),
    path(
        "orders/<int:pk>/cancel/",
        views.OrderCancelView.as_view(),
        name="order_cancel",
    ),
    path("orders/current/download/", views.export_orders, name="export_current"),
    path("orders/<int:pk>/download/", views.export_orders, name="export_orders"),
    path("orders/add/", views.FreeOrderAddView.as_view(), name="free_order"),
    path("logs/", views.InventoryLogListView.as_view(), name="logs"),
    path(
        "logs/<int:pk>/",
        views.InventoryLogDetailView.as_view(),
        name="log_items",
    ),
    # path("pick_parts/", views.PickPartsView.as_view(), name="pick_parts"),
    path("sets/", views.JobSetsView.as_view(), name="job_sets"),
    path("sets/<int:pk>/", views.JobSetView.as_view(), name="job_set"),
    path("sets/all/", views.AllJobSetsView.as_view(), name="all_job_sets"),
    path("margins/", views.MarginView.as_view(), name="margins"),
    path(
        "prosthetist_items/",
        views.ProsthetistItemsView.as_view(),
        name="prosthetist_items",
    ),
    path(
        "prosthesis_list/",
        views.ProsthesisListView.as_view(),
        name="prosthesis_list",
    ),
    path(
        "prosthesis/<int:pk>/",
        views.ProsthesisEditView.as_view(),
        name="prosthesis_edit",
    ),
    path(
        "prosthesis/add/",
        views.ProsthesisEditView.as_view(),
        name="prosthesis_add",
    ),
]

ortoreal/ortoreal/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("select2/", include("django_select2.urls")),
    path("", include("inventory.urls", namespace="inventory")),
    path("", include("clients.urls", namespace="clients")),
    path("admin/", admin.site.urls),
]

ortoreal/inventory/views.py
import io
import urllib
from collections import defaultdict
from decimal import Decimal
from typing import Any, Dict

from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db import transaction
from django.db.models import (
    Case,
    CharField,
    Count,
    F,
    Max,
    Q,
    QuerySet,
    Sum,
    Value,
    When,
    Window,
)
from django.db.models.functions import Concat, RowNumber
from django.http.response import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.utils import timezone
from django.views import View

import django_tables2 as tables
from django_filters.views import FilterView
from django_tables2.export.views import ExportMixin
from django_tables2.paginators import LazyPaginator
from xlsxwriter.workbook import Workbook

from clients.models import Job
from inventory.filters import InventoryLogFilter, MarginFilter, PartFilter
from inventory.forms import (
    FreeOrderFormSet,
    InventoryAddForm,
    InventoryTakeForm,
    InvoiceNumberFormSet,
    ItemReturnFormSet,
    ItemTakeFormSet,
    JobSelectForm,
    PartAddFormSet,
    PickPartsFormSet,
    ProsthesisForm,
    ProsthesisSelectForm,
    ReceptionForm,
    ReceptionItemFormSet,
)
from inventory.models import InventoryLog, Invoice, Item, Order, Part, Prosthesis
from inventory.tables import (
    CurrentOrderTable,
    InventoryLogsTable,
    JobSetsTable,
    MarginTable,
    NomenclatureTable,
    OrdersTable,
    OrderTable,
    PartItemsTable,
    ProsthesisListTable,
    ProsthetistItemsTable,
    VendorExportTable,
    VendorOrdersTable,
)
from inventory.utils import (  # TODO; check_minimum_remainder,
    OrderedCounter,
    create_reserve,
    generate_zip,
    move_reserves_to_free_order,
    remove_excess_from_current_order,
    remove_reserve,
    reorg_reserves,
)

PARTS_PER_PAGE = 20

User = get_user_model()


class LoginRequiredMixin(LoginRequiredMixin):
    login_url = "/admin/login/"
    redirect_field_name = "next"


class NomenclatureListView(
    LoginRequiredMixin,
    UserPassesTestMixin,
    tables.SingleTableMixin,
    FilterView,
):
    """
    View номенклатуры.
    """

    table_class = NomenclatureTable
    model = Part
    paginate_by = PARTS_PER_PAGE
    template_name = "inventory/nomenclature.html"

    filterset_class = PartFilter

    def test_func(self) -> bool:
        return self.request.user.is_manager or self.request.user.is_staff

    def get_queryset(self) -> QuerySet[Any]:
        queryset = (
            Part.objects.filter(items__job=None)
            .order_by("vendor_code")
            .annotate(
                quantity=Concat(
                    Count("items", filter=Q(items__arrived=True)),
                    Value(" "),
                    "units",
                    output_field=CharField(),
                ),
                available=Count(
                    "items",
                    filter=Q(items__reserved=None, items__arrived=True),
                ),
                in_reserve=Count(
                    "items",
                    filter=Q(items__reserved__isnull=False, items__arrived=True),
                ),
            )
        )
        return queryset


class PartItemsListView(
    LoginRequiredMixin, UserPassesTestMixin, tables.SingleTableView
):
    """
    View списка комплектующих данной модели на складе.
    """

    table_class = PartItemsTable
    paginate_by = PARTS_PER_PAGE

    def test_func(self) -> bool:
        return self.request.user.is_manager

    def get_part(self):
        pk = self.kwargs.get("pk")
        part = get_object_or_404(Part, pk=pk)
        return part

    def get_queryset(self) -> QuerySet[Any]:
        queryset = Item.objects.filter(
            part=self.get_part(), job=None, arrived=True
        ).order_by("-date")
        return queryset


class ReceptionView(LoginRequiredMixin, View):
    """
    Приход.
    """

    def get(self, request, *args, **kwargs):
        form = ReceptionForm()
        formset = ReceptionItemFormSet()
        context = {
            "form": form,
            "formset": formset,
        }
        return render(request, "inventory/reception.html", context)

    def post(self, request, *args, **kwargs):
        form = ReceptionForm(request.POST)
        formset = ReceptionItemFormSet(request.POST)

        if form.is_valid():
            invoice = form.cleaned_data["invoice"]
            return redirect("inventory:reception_invoice", pk=invoice.pk)

        if formset.is_valid() and formset.forms:
            date = form.cleaned_data["date"]
            operation = InventoryLog.Operation.RECEPTION
            comment = form.cleaned_data["comment"]
            # фильтр: не назначен склад, не в текущем заказе и не имеет счёта
            # сортировка по дате резерва, без резерва - в последнюю очередь
            ordered_items = Item.objects.filter(
                arrived=False, order__is_current=False, invoice__isnull=True
            ).order_by(F("reserved__date").asc(nulls_last=True), F("id").asc())

            batch_update_items = []
            for fs_form in formset:
                quantity = fs_form.cleaned_data["quantity"]
                print(quantity)
                # Если кол-во не указано или <= 0, то пропустить
                if quantity is None or quantity <= 0:
                    continue
                log = InventoryLog.objects.create(
                    operation=operation,
                    comment=comment,
                )
                part = fs_form.cleaned_data["part"]
                price = fs_form.cleaned_data["price"]
                vendor2 = fs_form.cleaned_data["vendor2"]
                matching_ordered = ordered_items.filter(part=part)
                # Проверяем, есть ли пришедшие в заказанных,
                # добавляем склад и заменяем дату на дату прихода
                log_items = []
                if matching_ordered.exists():
                    match_quantity = len(matching_ordered)
                    if quantity > match_quantity:
                        quantity -= match_quantity
                    else:
                        match_quantity = quantity
                        # обнуляем кол-во, чтобы не создавать новые записи
                        quantity = 0
                    for item in matching_ordered[:match_quantity]:
                        item.date = date
                        item.arrived = True
                        item.vendor2 = vendor2
                        batch_update_items.append(item)
                        log_items.append(item)
                # Если в приходе больше, чем заказанных,
                # создаём записи для остальных
                if quantity:
                    batch_create_items = [
                        Item(
                            part=part,
                            arrived=True,
                            vendor2=vendor2,
                            price=price,
                            date=date,
                        )
                    ] * quantity
                    Item.objects.bulk_create(batch_create_items)
                    created_items = Item.objects.filter(
                        part=part,
                        arrived=True,
                        vendor2=vendor2,
                        price=price,
                        date=date,
                    )
                    log_items += list(created_items)

                # Объединяем созданные и обновляемые записи для лога
                log.items.set(log_items)

            Item.objects.bulk_update(batch_update_items, ["date", "arrived", "price"])

            return redirect("inventory:logs")

        context = {
            "form": form,
            "formset": formset,
        }

        return render(request, "inventory/reception.html", context)


class ReceptionInvoiceView(LoginRequiredMixin, View):
    """
    Приход.
    """

    def get(self, request, pk):
        invoice = get_object_or_404(Invoice, pk=pk)
        form = ReceptionForm(initial={"invoice": invoice})
        queryset = self.get_queryset(invoice)
        formset = ReceptionItemFormSet(initial=queryset.values("part", "quantity"))
        context = {
            "form": form,
            "formset": formset,
        }
        return render(request, "inventory/reception.html", context)

    def post(self, request, pk):
        form = ReceptionForm(request.POST)
        formset = ReceptionItemFormSet(request.POST)

        if not form.is_valid():
            return redirect("inventory:reception")

        invoice = form.cleaned_data["invoice"]

        if formset.is_valid() and formset.forms:
            date = form.cleaned_data["date"]
            operation = InventoryLog.Operation.RECEPTION
            comment = form.cleaned_data["comment"]
            # фильтр: не назначен склад, не в текущем заказе и не имеет счёта
            # сортировка по дате резерва, без резерва - в последнюю очередь
            ordered_items = invoice.items.filter(
                arrived=False, order__is_current=False
            ).order_by(F("reserved__date").asc(nulls_last=True), F("id").asc())

            batch_update_items = []
            for fs_form in formset:
                quantity = fs_form.cleaned_data["quantity"]
                # Если кол-во не указано или <= 0, то пропустить
                if quantity is None or quantity <= 0:
                    continue
                log = InventoryLog.objects.create(
                    operation=operation,
                    comment=comment,
                    invoice=invoice,
                    order=invoice.order,
                )
                part = fs_form.cleaned_data["part"]
                price = fs_form.cleaned_data["price"]
                vendor2 = fs_form.cleaned_data["vendor2"]

ortoreal/templates/inventory/form_table.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  {% if adding %}
    Добавить
  {% elif taking %}
    Взять
  {% elif returning %}
    Возврат
  {% endif %}
{% endblock title %}
{% block content %}
  <div class="card-body">
    <form method="post"
          enctype="multipart/form-data"
          id="form-container"
          class="{% if adding %} adding {% elif taking %} taking {% endif %}">
      {% csrf_token %}
      {{ form.as_p }}
      {{ formset.management_form }}
      <div class="table-responsive">
        <link rel="stylesheet" href="{% static "css/form_table.css" %}"/>
        <table class="table table-bordered align-middle">
          {% include "includes/form_table_head.html" with form=formset.0 %}
          {% for item_form in formset %}
            {% include "./includes/form_item_row.html" with form=item_form %}
          {% endfor %}
        </table>
        <div class="button-row position-relative">
          <button id="add-form" type="button" class="btn btn-secondary">+</button>
          <button id="remove-form" type="button" class="btn btn-danger">-</button>
          <button id="submit-form"
                  type="submit"
                  class="btn btn-primary position-absolute end-0">
            {% if adding %}
              Добавить
            {% elif taking %}
              Взять
            {% endif %}
          </button>
        </div>
      </div>
    </form>
  </div>
  <script src="{% static 'js/form_select2.js' %}"></script>
{% endblock content %}

ortoreal/templates/inventory/inventorylog.html
{% extends "base.html" %}
{% load static %}
{% load django_bootstrap5 %}
{% block title %}
  История операций на складе
{% endblock title %}
{% block static %}
  <link rel="stylesheet" href="{% static "css/table.css" %}" />
  <script src="{% static 'js/table_row_link.js' %}"></script>
{% endblock static %}
{% block content %}
  <div class="card-body">
    {% if filter %}
      <form action="" method="get" class="form">
        {% csrf_token %}
        <div class="input-group">
          {% for field in filter.form %}
            {% bootstrap_field field field_class="col" layout="floating" wrapper_class="col me-2 mb-2" %}
          {% endfor %}
        </div>
        {% bootstrap_button "Фильтровать" %}
      </form>
      <br />
    {% endif %}
    {% load django_tables2 %}
    {% render_table table %}
  </div>
{% endblock content %}

ortoreal/templates/inventory/items.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  {{ part }}
{% endblock title %}
{% block static %}
  <link rel="stylesheet" href="{% static "css/table.css" %}"/>
{% endblock static %}
{% block content %}
  <h3 class="text-center">{{ part }}</h3>
  <div class="table-responsive">
    <table class="table table-striped table-bordered align-middle">
      {% include "includes/table_head.html" %}
      <tbody>
        {% for row in page_obj %}
          {% include "./includes/item_row.html" %}
        {% endfor %}
      </tbody>
    </table>
  </div>
  {% include "includes/paginator.html" %}
{% endblock content %}

ortoreal/templates/inventory/job_set.html
{% extends "base.html" %}
{% load static %}
{% load user_filters %}
{% block title %}
  Выбрать комплектацию
{% endblock title %}
{% block content %}
  <div class="card-body">
    <form method="post"
          enctype="multipart/form-data"
          id="form-container"
          class=" adding">
      {% csrf_token %}
      {% for field in form %}
        <div class="row g-3 align-items-center pb-1">
          <div class="col-auto">
            <label for="{{ field.id_for_label }}">
              {{ field.label }}
              {% if field.field.required %}<span class="required text-danger">*</span>{% endif %}
            </label>
          </div>
          <div class="col-auto">{{ field|addclass:'form-control' }}</div>
        </div>
      {% endfor %}
      {{ formset.management_form }}
      <div class="table-responsive">
        <link rel="stylesheet" href="{% static "css/form_table.css" %}" />
        <link rel="stylesheet" href="{% static "css/take_table.css" %}" />
        <table class="table table-bordered align-middle">
          {% include "includes/form_table_head.html" with form=formset.0 %}
          {% for form in formset %}
            <tr class="input-row text-center">
              {% for hidden in form.hidden_fields %}{{ hidden }}{% endfor %}
              {% for field in form.visible_fields %}
                <td class="item-form {% if field.errors %}alert-td{% endif %}"
                    title="{% for error in field.errors %}{{ error }}{% if not forloop.last %}&#10;&#013;{% endif %}{% endfor %}">
                  {{ field }}
                </td>
              {% endfor %}
            </tr>
          {% endfor %}
        </table>
        {% if formset.forms %}
          <div class="button-row position-relative">
            <button id="add-form" type="button" class="btn btn-secondary">+</button>
            <button id="remove-form" type="button" class="btn btn-danger">-</button>
            <button id="submit-form"
                    type="submit"
                    class="btn btn-primary position-absolute end-0">Сохранить комплектацию</button>
          </div>
        {% endif %}
      </div>
    </form>
  </div>
  <script src="{% static 'js/inventory/set_selection.js' %}"></script>
{% endblock content %}

ortoreal/templates/inventory/margin_list.html
{% extends "base.html" %}
{% load static %}
{% load user_filters %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% block title %}
  Маржа
{% endblock title %}
{% block static %}
  <link rel="stylesheet" href="{% static "css/table.css" %}" />
  {% comment %}
  <script src="{% static 'js/table_row_link.js' %}"></script>
  {% endcomment %}
{% endblock static %}
{% block content %}
  {{ filter.form.media }}
  <div class="card-body">
    {% if filter %}
      <form action="" method="get" class="form">
        {% csrf_token %}
        <div class="input-group">
          {% for field in filter.form %}
            {% bootstrap_field field field_class="col" layout="floating" wrapper_class="col me-2 mb-2" %}
          {% endfor %}
        </div>
        {% bootstrap_button button_type="submit" content="Фильтровать" %}
      </form>
      <br />
    {% endif %}
    {% load django_tables2 %}
    {% render_table table %}
  </div>
{% endblock content %}

ortoreal/templates/inventory/order_list.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  Заказы
{% endblock title %}
{% block static %}
  <link rel="stylesheet" href="{% static "css/table.css" %}"/>
  <link rel="stylesheet" href="{% static "css/item_pill.css" %}"/>
  <script src="{% static 'js/table_row_link.js' %}"></script>
{% endblock static %}
{% block content %}
  {% load django_tables2 %}
  <div class="card-body">
    {% render_table table %}
  </div>
{% endblock content %}

ortoreal/templates/inventory/parts.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  Модели комплектующих
{% endblock title %}
{% block static %}
  <link rel="stylesheet" href="{% static "css/table.css" %}"/>
{% endblock static %}
{% block content %}
  <div class="table-responsive">
    <table class="table table-striped table-bordered align-middle">
      {% include "includes/table_head.html" %}
      <tbody>
        {% for row in page_obj %}
          {% include "./includes/part_row.html" %}
        {% endfor %}
      </tbody>
    </table>
  </div>
  {% include "includes/paginator.html" %}
{% endblock content %}

ortoreal/templates/inventory/pick_parts.html
{% extends "base.html" %}
{% load static %}
{% load user_filters %}
{% block title %}
  Выбрать комплектацию
{% endblock title %}
{% block content %}
  <div class="card-body">
    <form method="post"
          enctype="multipart/form-data"
          id="form-container"
          class=" adding">
      {% csrf_token %}
      {% for form in forms %}
        {% for field in form %}
          <div class="row g-3 align-items-center pb-1">
            <div class="col-auto">
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                {% if field.field.required %}<span class="required text-danger">*</span>{% endif %}
              </label>
            </div>
            <div class="col-auto">{{ field|addclass:'form-control' }}</div>
          </div>
        {% endfor %}
      {% endfor %}
      {{ formset.management_form }}
      <div class="table-responsive">
        <link rel="stylesheet" href="{% static "css/form_table.css" %}" />
        <link rel="stylesheet" href="{% static "css/take_table.css" %}" />
        <table class="table table-bordered align-middle">
          {% include "includes/form_table_head.html" with form=formset.0 %}
          {% for form in formset %}
            <tr class="input-row text-center">
              {% for hidden in form.hidden_fields %}{{ hidden }}{% endfor %}
              {% for field in form.visible_fields %}
                <td class="item-form {% if field.errors %}alert-td{% endif %}"
                    title="{% for error in field.errors %}{{ error }}{% if not forloop.last %}&#10;&#013;{% endif %}{% endfor %}">
                  {{ field }}
                </td>
              {% endfor %}
            </tr>
          {% endfor %}
        </table>
        {% if formset.forms %}
          <div class="button-row position-relative">
            <button id="add-form" type="button" class="btn btn-secondary">+</button>
            <button id="remove-form" type="button" class="btn btn-danger">-</button>
            <button id="submit-form"
                    type="submit"
                    class="btn btn-primary position-absolute end-0">Сохранить комплектацию</button>
          </div>
        {% endif %}
      </div>
    </form>
  </div>
  <script src="{% static 'js/inventory/set_selection.js' %}"></script>
{% endblock content %}

ortoreal/templates/inventory/prosthesis_form.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% load static %}
{% block title %}
  Добавить/изменить протез
{% endblock title %}
{% block content %}
  <div class="card-body">
    <form method="post" enctype="multipart/form-data" id="form-container">
      {% csrf_token %}
      {% bootstrap_form form %}
      <div class="button-row position-relative">
        <button id="submit-form"
                type="submit"
                class="btn btn-primary position-absolute end-0">Добавить/изменить</button>
      </div>
    </form>
  </div>
{% endblock content %}

ortoreal/templates/inventory/prosthesis_list.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  Протезы
{% endblock title %}
{% block static %}
  <link rel="stylesheet" href="{% static "css/table.css" %}" />
  <link rel="stylesheet" href="{% static "css/item_pill.css" %}" />
{% endblock static %}
{% block content %}
  {% load django_tables2 %}
  <div class="card-body">
    <h4>Протезы</h4>
    {% render_table table %}
    <a class="btn btn-primary" href={% url 'inventory:prosthesis_add' %}>Добавить</a>
  </div>
  <script src="{% static 'js/table_row_link.js' %}"></script>
{% endblock content %}

ortoreal/templates/inventory/prosthetist_items_list.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  Инвентарь у протезистов
{% endblock title %}
{% block static %}
  <link rel="stylesheet" href="{% static "css/table.css" %}" />
  <link rel="stylesheet" href="{% static "css/item_pill.css" %}" />
{% endblock static %}
{% block content %}
  {% load django_tables2 %}
  <div class="card-body">{% render_table table %}</div>
  <script src="{% static 'js/table_row_link.js' %}"></script>
{% endblock content %}

ortoreal/templates/inventory/reception.html
{% extends "base.html" %}
{% load static %}
{% load user_filters %}
{% comment %}
{% block static %}
  <script src="{% static 'js/inventory/reception.js' %}"></script>
{% endblock static %}
{% endcomment %}
{% block title %}
  Приход
{% endblock title %}
{% block content %}
  <div class="card-body">
    <form method="post"
          enctype="multipart/form-data"
          id="form-container"
          class=" adding">
      {% csrf_token %}
      {% for field in form.visible_fields %}
        <div class="row g-3 align-items-center pb-1">
          <div class="col-auto">
            <label for="{{ field.id_for_label }}">
              {{ field.label }}
              {% if field.field.required %}<span class="required text-danger">*</span>{% endif %}
            </label>
          </div>
          <div class="col-auto">{{ field|addclass:'form-control' }}</div>
        </div>
      {% endfor %}
      {{ formset.management_form }}
      <div class="table-responsive">
        <link rel="stylesheet" href="{% static "css/form_table.css" %}" />
        <link rel="stylesheet" href="{% static "css/take_table.css" %}" />
        <table class="table table-bordered align-middle">
          {% include "includes/form_table_head.html" with form=formset.0 %}
          {% for form in formset %}
            {% include "./includes/form_item_row.html" %}
          {% endfor %}
        </table>
        <div class="button-row position-relative">
          <button id="add-form" type="button" class="btn btn-secondary">+</button>
          <button id="remove-form" type="button" class="btn btn-danger">-</button>
          <button id="submit-form"
                  type="submit"
                  class="btn btn-primary position-absolute end-0">Добавить</button>
        </div>
      </div>
    </form>
  </div>
  <script src="{% static 'js/inventory/set_selection.js' %}"></script>
{% endblock content %}

ortoreal/templates/inventory/take_items.html
{% extends "base.html" %}
{% load static %}
{% load user_filters %}
{% block title %}
  {% if taking %}
    Расход
  {% else %}
    Возврат
  {% endif %}
{% endblock title %}
{% block content %}
  <div class="card-body">
    <form method="post"
          enctype="multipart/form-data"
          id="form-container"
          class="taking">
      {% csrf_token %}
      {% for field in form.visible_fields %}
        <div class="row g-3 align-items-center pb-1">
          <div class="col-auto">
            <label for="{{ field.id_for_label }}">
              {{ field.label }}
              {% if field.field.required %}<span class="required text-danger">*</span>{% endif %}
            </label>
          </div>
          <div class="col-auto">{{ field|addclass:'form-control' }}</div>
        </div>
      {% endfor %}
      {{ formset.management_form }}
      {% if form.is_valid and formset.forms %}
        <hr/>
        <div class="table-responsive">
          <link rel="stylesheet" href="{% static "css/form_table.css" %}"/>
          <table class="table table-bordered align-middle">
            {% if taking %}
              <link rel="stylesheet" href="{% static "css/take_table.css" %}"/>
              {% include "includes/form_table_head.html" with form=formset.0 %}
              {% for form in formset %}
                {% include "./includes/form_item_row.html" %}
              {% endfor %}
            {% elif formset.forms %}
              <link rel="stylesheet" href="{% static 'css/return_table.css' %}"/>
              {% include "includes/form_table_head.html" with form=formset.0 %}
              {% for form in formset %}
                {% include "./includes/form_return_row.html" %}
              {% endfor %}
            {% endif %}
          </table>
        </div>
        <div class="button-row position-relative">
          {% if taking %}
            <button id="add-form" type="button" class="btn btn-secondary">+</button>
            <button id="remove-form" type="button" class="btn btn-danger">-</button>
            <button id="take-button"
                    type="submit"
                    class="btn btn-primary position-absolute end-0">Взять</button>
          {% else %}
            <button id="return-button"
                    type="submit"
                    class="btn btn-primary position-absolute end-0">Вернуть</button>
          {% endif %}
        </div>
      {% endif %}
    </form>
  </div>
  {% if taking %}
    <script src="{% static 'js/inventory/take_page.js' %}"></script>
  {% else %}
    <script src="{% static 'js/inventory/return_page.js' %}"></script>
  {% endif %}
{% endblock content %}

ortoreal/templates/inventory/vendororder_list.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  Заказы
{% endblock title %}
{% block static %}
  <link rel="stylesheet" href="{% static "css/table.css" %}" />
  <link rel="stylesheet" href="{% static "css/item_pill.css" %}" />
  <script src="{% static 'js/table_row_link.js' %}"></script>
{% endblock static %}
{% block content %}
  {% load django_tables2 %}
  <div class="card-body">{% render_table orders_table %}</div>
{% endblock content %}