ortoreal/clients/urls.py
from django.urls import include, path

from clients import views

app_name = "clients"

urlpatterns = [
    path("", views.ClientsListView.as_view(), name="index"),
    path("contacts/", views.contacts, name="contacts"),
    path("contacts/add/", views.add_contact, name="add_contact"),
    path("contacts/edit/<int:pk>", views.edit_contact, name="edit_contact"),
    path("clients/", views.ClientsListView.as_view(), name="clients"),
    path("jobs/<int:pk>/", views.JobDetailView.as_view(), name="job"),
    path("job/add/", views.JobCreateView.as_view(), name="add_job"),
    # path("jobs/all/", views.AllClientsListView.as_view(), name="all_jobs"),
    path("clients/<int:pk>/", views.ClientView.as_view(), name="client"),
    path(
        "clients/<int:pk>/add_job/",
        views.JobCreateView.as_view(),
        name="add_job_client",
    ),
    path(
        "clients/<int:pk>/add_contact/",
        views.ContactCreateView.as_view(),
        name="add_contact",
    ),
    path(
        "clients/add/",
        views.ClientCreateView.as_view(),
        name="add_client",
    ),
    path(
        "jobs/<int:pk>/status/",
        views.JobChangeStatusView.as_view(),
        name="change_job_status",
    ),
    path(
        "jobs/<int:pk>/status/<int:status_pk>/",
        views.JobChangeStatusView.as_view(),
        name="edit_job_status",
    ),
]

ortoreal/ortoreal/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("select2/", include("django_select2.urls")),
    path("", include("inventory.urls", namespace="inventory")),
    path("", include("clients.urls", namespace="clients")),
    path("admin/", admin.site.urls),
]

ortoreal/clients/models.py
import uuid
from tabnanny import verbose
from typing import Iterable, Optional

from django.contrib.auth import get_user_model
from django.db import IntegrityError, models
from django.db.models import CharField, Value
from django.db.models.functions import Cast, Concat, Substr
from django.urls import reverse
from django.utils import timezone
from django.utils.formats import date_format
from django.utils.safestring import mark_safe
from django.utils.translation import gettext_lazy as _

from phonenumber_field.modelfields import PhoneNumberField

User = get_user_model()


class Status(models.Model):
    class StatusNames(models.TextChoices):
        IN_WORK = "in work", _("принят в работу")
        ISSUED = "issued", _("выдан")
        DOCS_SUBMITTED = "docs submitted", _("документы сданы")
        PAYMENT_TO_CLIENT = "payment to client", _("оплата клиенту")
        PAYMENT = "payment", _("оплата")

    class StatusColors(models.TextChoices):
        IN_WORK = "in work", "B6D7A8"
        ISSUED = "issued", "6AA84F"
        DOCS_SUBMITTED = "docs submitted", "34A853"
        PAYMENT_TO_CLIENT = "payment to client", "00FFFF"
        PAYMENT = "payment", "6D9EEB"

    name = models.CharField(
        "статус",
        max_length=150,
        choices=StatusNames.choices,
        default=StatusNames.IN_WORK,
        blank=False,
        null=False,
    )
    job = models.ForeignKey(
        "Job",
        verbose_name="работа",
        on_delete=models.CASCADE,
        related_name="statuses",
    )
    date = models.DateTimeField("дата", default=timezone.now)
    comment = models.TextField("комментарий", blank=True)
    color = models.CharField(
        "цвет",
        max_length=150,
        choices=StatusColors.choices,
        default=StatusColors.IN_WORK,
        blank=False,
        null=False,
    )

    def __str__(self) -> str:
        date = date_format(
            timezone.localdate(self.date), format="SHORT_DATE_FORMAT", use_l10n=True
        )
        return f"{self.get_name_display()} {date}"

    class Meta:
        verbose_name = "статус"
        verbose_name_plural = "статусы"

    def save(self, *args, **kwargs):
        self.color = self.name
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse(
            "clients:edit_job_status",
            kwargs={"pk": self.job.pk, "status_pk": self.pk},
        )


class ContactTypeChoice(models.Model):
    name = models.CharField("название опции", max_length=128, blank=True)
    prosthetist = models.ForeignKey(
        User,
        verbose_name="протезист",
        limit_choices_to={"is_prosthetist": True},
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )

    class Meta:
        verbose_name = "откуда обратились"
        verbose_name_plural = "откуда обратились"

    def __str__(self) -> str:
        return str(self.prosthetist or self.name)


class Client(models.Model):
    class Region(models.TextChoices):
        MOSCOW = "Moscow", _("Москва")
        MOSCOW_REGION = "Moscow region", _("Московская область")

    def client_directory_path(self, filename):
        """
        Название директория для файлов клиента.
        """
        filename = (
            str(self.id)
            + "_"
            + str(uuid.uuid4())[:8]
            + "."
            + filename.rsplit(".", 1)[-1]
        )
        return f"clients/{self.id}/{filename}"

    last_name = models.CharField(
        _("last name"), max_length=150, blank=False, default=None
    )
    first_name = models.CharField(
        _("first name"), max_length=150, blank=False, default=None
    )
    surname = models.CharField(_("отчество"), max_length=150, blank=True)
    birth_date = models.DateField(_("дата рождения"), blank=True, null=True)
    phone = models.CharField(_("телефон"), blank=True, null=True)
    # phone = PhoneNumberField(_("телефон"), blank=False, null=False, unique=True)
    address = models.TextField(_("адрес"), max_length=1000)
    prosthetist = models.ForeignKey(
        User,
        verbose_name="протезист",
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        limit_choices_to={"is_prosthetist": True},
    )
    region = models.CharField(
        "регион",
        max_length=128,
        choices=Region.choices,
    )
    snils = models.CharField("СНИЛС", blank=True, null=True)
    snils_scan = models.FileField(
        "скан СНИЛС", upload_to=client_directory_path, blank=True, null=True
    )
    ipr = models.FileField(
        "ИПР", upload_to=client_directory_path, blank=True, null=True
    )
    debt = models.DecimalField(
        "Долги, руб.", max_digits=11, decimal_places=2, blank=True, null=True
    )

    sprmse = models.FileField(
        "CпрМСЭ", upload_to=client_directory_path, blank=True, null=True
    )
    notes = models.CharField("примечания", blank=True, null=True)

    def get_phone_display(self):
        return self.phone.as_national.replace(" ", "")

    def get_full_name(self):
        full_name = f"{self.last_name} {self.first_name}"
        if self.surname:
            full_name += " " + self.surname
        return full_name

    def get_name_with_initials(self):
        name = f"{self.last_name} {self.first_name[0]}."
        if self.surname:
            name += f"{self.surname[0]}."
        return name

    @property
    def full_name(self):
        return self.get_full_name()

    def get_latest_job_statuses(self):
        statuses = []
        for job in self.jobs.all():
            statuses.append(job.status_display)
        return statuses

    class Meta:
        verbose_name = "клиент"
        verbose_name_plural = "клиенты"

    def __str__(self) -> str:
        return self.get_full_name()

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        # if self.status:
        #     Status.objects.create(name=self.status, client=self)

    def get_absolute_url(self):
        return reverse("clients:client", kwargs={"pk": self.pk})


class Passport(models.Model):
    def passport_directory_path(self, filename):
        """
        Название директория для файлов клиента.
        """
        filename = (
            str(self.id)
            + "_"
            + str(uuid.uuid4())[:8]
            + "."
            + filename.rsplit(".", 1)[-1]
        )
        return f"passport/{self.id}/{filename}"

    client = models.ForeignKey(
        Client,
        verbose_name="клиент",
        on_delete=models.CASCADE,
        related_name="passport",
    )
    series = models.CharField("серия", max_length=4)
    number = models.CharField("номер", max_length=6)
    date_of_issue = models.DateField("дата выдачи")
    who_issued = models.CharField("кем выдан", max_length=1024)
    division_code = models.CharField("код подразделения", max_length=7)
    scan = models.FileField(
        "скан", upload_to=passport_directory_path, blank=True, null=True
    )

    class Meta:
        verbose_name = "паспортные данные"


class BankDetails(models.Model):
    client = models.ForeignKey(
        Client,
        verbose_name="клиент",
        on_delete=models.CASCADE,
        related_name="bank_details",
    )
    account_number = models.CharField("№ Счёта (р/с)", max_length=20)
    bank = models.CharField("в банке (название)", max_length=1024)
    BIC = models.CharField("БИК", max_length=8)
    correspondent_account = models.CharField("к/с", max_length=20)

    class Meta:
        verbose_name = "реквизиты"


class Contact(models.Model):
    class YesNo(models.TextChoices):
        YES = "yes", _("да")
        NO = "no", _("нет")

    client = models.ForeignKey(
        Client,
        verbose_name="клиент",
        on_delete=models.CASCADE,
        related_name="contacts",
    )
    call_date = models.DateField(_("дата звонка"), default=timezone.now)
    last_prosthesis_date = models.CharField(
        "предыдущий протез",
        max_length=150,
        default="первичн.",
        blank=True,
        help_text="примерная дата получения последнего протеза",
    )
    prosthesis_type = models.CharField("протез", max_length=150, blank=True)
    call_result = models.CharField(_("результат звонка"), max_length=1024, blank=True)
    # comment = models.CharField(
    #     _("комментарий"),
    #     max_length=1024,
    #     blank=True,
    #     help_text="комментарий протезиста",
    # )

    MTZ_date = models.DateField(_("МТЗ"), blank=True, null=True)
    result = models.CharField(
        _("результат"),
        max_length=16,
        blank=True,
        choices=YesNo.choices,
        help_text="согласились или нет",
    )

    @classmethod
    def get_field_names(cls):
        return [f.verbose_name for f in cls._meta.fields]

    class Meta:
        verbose_name = "обращение"
        verbose_name_plural = "обращения"

    def __str__(self) -> str:
        return f"{self.client}"

    # def save(self, *args, **kwargs):
    #     """
    #     Создаём работу, если клиент согласился в обращении.
    #     """
    #     super().save(*args, **kwargs)
    #     if self.result == Contact.YesNo.YES:
    #         Job.objects.get_or_create(client=self.client)


class Comment(models.Model):
    contact = models.ForeignKey(
        Contact,
        verbose_name="контакт",
        on_delete=models.CASCADE,
        related_name="comments",
    )
    text = models.TextField("комментарий(примечание)")
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "комментарий"
        verbose_name_plural = "комментарии"

    def __str__(self) -> str:
        return f"{self.date.date()} {self.text[:20]}"


class Job(models.Model):
    client = models.ForeignKey(
        Client,
        verbose_name="клиент",
        on_delete=models.CASCADE,
        related_name="jobs",
    )
    how_contacted = models.ForeignKey(
        ContactTypeChoice,
        verbose_name="откуда обратились",
        on_delete=models.SET_NULL,

ortoreal/clients/forms.py
from collections.abc import Mapping
from typing import Any

from django import forms
from django.contrib.auth import get_user_model
from django.core.files.base import File
from django.db.models.base import Model
from django.forms.utils import ErrorList
from django.utils import timezone

from clients.models import Client, Comment, Contact, Job, Status

User = get_user_model()


class DatePicker(forms.DateInput):
    input_type = "date"


class DateTimePicker(forms.DateInput):
    input_type = "datetime-local"


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = "__all__"
        exclude = ["client"]

        widgets = {
            "call_date": DatePicker(attrs={"value": timezone.now}, format="%Y-%m-%d"),
            "MTZ_date": DatePicker(attrs={"value": timezone.now}, format="%Y-%m-%d"),
        }


class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = "__all__"


class JobForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["date"].widget = DatePicker(
            attrs={
                "value": timezone.now,
            },
            format="%Y-%m-%d",
        )

    class Meta:
        model = Job
        fields = [
            "client",
            "how_contacted",
            "prosthetist",
            "prosthesis",
            "date",
        ]


class JobClientForm(JobForm):
    class Meta:
        model = Job
        fields = [
            "how_contacted",
            "prosthetist",
            "prosthesis",
            "date",
        ]


class ClientContactForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = [
            "last_name",
            "first_name",
            "surname",
            "phone",
            "address",
            "region",
            "birth_date",
        ]
        widgets = {
            "birth_date": DatePicker(),
            "address": forms.Textarea(attrs={"rows": 1}),
        }


choices = Status.StatusNames.choices

choice_field = forms.ChoiceField(choices=choices)


class JobStatusSelectForm(forms.ModelForm):
    class Meta:
        model = Status
        fields = [
            "name",
            "date",
            "comment",
        ]
        widgets = {
            "date": DateTimePicker(format="%Y-%m-%d %H:%M"),
        }

ortoreal/templates/clients/add.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% load static %}
{% block title %}
  Добавить нового клиента
{% endblock title %}
{% block content %}
  <div class="card-body">
    <h4>Добавить нового клиента</h4>
    {% include "includes/form_errors.html" %}
    <form method="post" enctype="multipart/form-data" id="form-container">
      {% csrf_token %}
      {% bootstrap_form form_client %}
      {% bootstrap_form form_contact %}
      <div class="button-row position-relative">
        <button id="submit-form"
                type="submit"
                class="btn btn-primary position-absolute end-0">Добавить</button>
      </div>
    </form>
  </div>
{% endblock content %}

ortoreal/templates/clients/client.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% load static %}
{% block title %}
  {% if job %}
    {{ job.client }}. {{ job.status_display }}
  {% else %}
    {{ client }} - {{ client.get_region_display }}
  {% endif %}
{% endblock title %}
{% block static %}
  <link rel="stylesheet" href="{% static "css/table.css" %}" />
  <link rel="stylesheet" href="{% static "css/item_pill.css" %}" />
  <link rel="stylesheet" href="{% static "css/status_pill.css" %}" />
{% endblock static %}
{% block content %}
  <div class="card-body">
    <div class="row">
      <div class="col-3">
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {% bootstrap_form form %}
          <input type="submit" value="Сохранить">
        </form>
      </div>
      {% load django_tables2 %}
      <div class="col">
        <h3>
          {% if job %}
            {{ job.client }}. {{ job.status_display }}
          {% else %}
            {{ client }} - {{ client.get_region_display }}
          {% endif %}
        </h3>
        <div class="row">
          <a class="btn btn-secondary col"
             href="{% url 'clients:add_contact' pk=client.pk %}">Добавить обращение</a>
          <a class="btn btn-primary col"
             href="{% url 'clients:add_job_client' pk=client.pk %}">Добавить работу</a>
        </div>
        <div class="row">{% render_table table %}</div>
      </div>
    </div>
  </div>
  <script src="{% static 'js/table_row_link.js' %}"></script>
{% endblock content %}

ortoreal/templates/clients/client_list.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  Заказы
{% endblock title %}
{% block static %}
  <link rel="stylesheet" href="{% static "css/table.css" %}" />
  <link rel="stylesheet" href="{% static "css/status_pill.css" %}" />
{% endblock static %}
{% block content %}
  {% load django_tables2 %}
  <div class="card-body">
    <div class="row">
      <a class="btn btn-secondary col" href="{% url 'clients:add_client' %}">Добавить обращение/клиента</a>
      <a class="btn btn-primary col" href="{% url 'clients:add_job' %}">Добавить работу</a>
    </div>
    {% render_table table %}
  </div>
  <script src="{% static 'js/table_row_link.js' %}"></script>
{% endblock content %}

ortoreal/templates/clients/contact_add.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% load static %}
{% block title %}
  Добавить обращение для {{ client }}
{% endblock title %}
{% block content %}
  <div class="card-body">
    <h3>Обращение для {{ client }}</h3>
    <form method="post" enctype="multipart/form-data" id="form-container">
      {% csrf_token %}
      {% bootstrap_form form %}
      <div class="button-row position-relative">
        <button id="submit-form"
                type="submit"
                class="btn btn-primary position-absolute end-0">Добавить</button>
      </div>
    </form>
  </div>
{% endblock content %}

ortoreal/templates/clients/contacts.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  Обращения
{% endblock title %}
{% block static %}
  <link rel="stylesheet" href="{% static "css/table.css" %}"/>
{% endblock static %}

{% block content %}
  <div class="table-responsive">
  <table class="table table-striped table-bordered align-middle">
  {% include "includes/table_head.html" %}
    <tbody>
      {% for row in page_obj %}
        {% include "./includes/contact_row.html" %}
      {% endfor %}
    </tbody>
  </table>
</div>
{% include "includes/paginator.html" %}
{% endblock content %}

ortoreal/templates/clients/create_contact copy.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  Добавить обращение
{% endblock title %}
{% block content %}
  <div class="card-body">
    {% include "includes/form_errors.html" %}
    <form method="post" enctype="multipart/form-data" id="form-container">
      {% csrf_token %}
      {{ form.as_p }}
      {{ formset.management_form }}
      {% for item_form in formset %}
        <div class="row item-form">{% include "includes/form_fields.html" with form=item_form %}</div>
      {% endfor %}
      <div class="button-row position-relative">
        <button id="add-form" type="button" class="btn btn-secondary">+</button>
        <button id="remove-form" type="button" class="btn btn-danger">-</button>
        <button id="submit-form"
                type="submit"
                class="btn btn-primary position-absolute end-0">Добавить</button>
      </div>
    </form>
  </div>
  <script src="{% static 'js/form_temp.js' %}"></script>
{% endblock content %}

ortoreal/templates/clients/create_contact.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  Добавить обращение
{% endblock title %}
{% block content %}
  <div class="card-body">
    {% include "includes/form_errors.html" %}
    <form method="post" enctype="multipart/form-data" id="form-container">
      {% csrf_token %}
      {{ form.as_p }}
      {{ formset.management_form }}
      {% for item_form in formset %}
        <div class="row item-form">{% include "includes/form_fields.html" with form=item_form %}</div>
      {% endfor %}
      <div class="button-row position-relative">
        <button id="add-form" type="button" class="btn btn-secondary">+</button>
        <button id="remove-form" type="button" class="btn btn-danger">-</button>
        <button id="submit-form"
                type="submit"
                class="btn btn-primary position-absolute end-0">Добавить</button>
      </div>
    </form>
  </div>
  <script src="{% static 'js/form_temp.js' %}"></script>
{% endblock content %}

ortoreal/templates/clients/job_add.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% load static %}
{% block title %}
  Добавить работу
  {% if client %}для {{ client }}{% endif %}
{% endblock title %}
{% block content %}
  <div class="card-body">
    {% if client %}
      <h4>Работа для {{ client }}</h4>
    {% else %}
      <h4>Добавить работу</h4>
    {% endif %}
    <form method="post" enctype="multipart/form-data" id="form-container">
      {% csrf_token %}
      {% bootstrap_form form %}
      <div class="button-row position-relative">
        <button id="submit-form"
                type="submit"
                class="btn btn-primary position-absolute end-0">Добавить</button>
      </div>
    </form>
  </div>
{% endblock content %}

ortoreal/templates/clients/job_detail.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% load static %}
{% block title %}
  {% if job %}
    {{ job.client }}. {{ job.status_display }}
  {% else %}
    {{ client }} - {{ client.get_region_display }}
  {% endif %}
{% endblock title %}
{% block static %}
  <link rel="stylesheet" href="{% static "css/table.css" %}" />
  <link rel="stylesheet" href="{% static "css/item_pill.css" %}" />
  <link rel="stylesheet" href="{% static "css/status_pill.css" %}" />
{% endblock static %}
{% block content %}
  <div class="card-body">
    <div class="row">
      {% comment %}
      <div class="col-3">
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {% bootstrap_form form %}
          <input type="submit" value="Сохранить">
        </form>
      {% endcomment %}
    </div>
    {% load django_tables2 %}
    <div class="col">
      <h3>
        {% if job %}
          {{ job.client }}. {{ job.status_display }}
        {% else %}
          {{ client }} - {{ client.get_region_display }}
        {% endif %}
      </h3>
      {% comment %}
            <div class="row">
            <a class="btn btn-secondary col" href="{% url 'clients:add_contact' pk=client.pk %}">Добавить обращение</a>
          <a class="btn btn-primary col" href="{% url 'clients:add_job_client' pk=client.pk %}">Добавить работу</a>
      </div>
      {% endcomment %}
      <div class="row">
        <div class="col">{% render_table table_statuses %}</div>
        <div class="col">{% render_table table_items %}</div>
      </div>
    </div>
  </div>
</div>
<script src="{% static 'js/table_row_link.js' %}"></script>
{% endblock content %}

ortoreal/templates/clients/job_list.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  {{ title }}
{% endblock title %}
{% block static %}
  <link rel="stylesheet" href="{% static "css/table.css" %}"/>
  <link rel="stylesheet" href="{% static "css/item_pill.css" %}"/>
  <script src="{% static 'js/table_row_link.js' %}"></script>
{% endblock static %}
{% block content %}
  {% load django_tables2 %}
  <div class="card-body">
    <h3>{{ title }}</h3>
    {% render_table table %}
  </div>
{% endblock content %}

ortoreal/templates/clients/job_status_change.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% load static %}
{% block title %}
  {{ job }}
{% endblock title %}
{% block content %}
  <div class="card-body">
    <h4>Изменить статус работы {{ job }}</h4>
    {% include "includes/form_errors.html" %}
    <form method="post" enctype="multipart/form-data" id="form-container">
      {% csrf_token %}
      {% bootstrap_form form %}
      <div class="button-row position-relative">
        <button id="submit-form"
                type="submit"
                class="btn btn-primary position-absolute end-0">Сохранить</button>
      </div>
    </form>
  </div>
{% endblock content %}