ortoreal/clients/urls.py
from django.urls import include, path

from clients import views

app_name = "clients"

urlpatterns = [
    path("", views.ClientsListView.as_view(), name="index"),
    path("contacts/", views.contacts, name="contacts"),
    path("contacts/add/", views.add_contact, name="add_contact"),
    path("contacts/edit/<int:pk>", views.edit_contact, name="edit_contact"),
    path("clients/", views.ClientsListView.as_view(), name="clients"),
    path("jobs/<int:pk>/", views.JobDetailView.as_view(), name="job"),
    path("job/add/", views.JobCreateView.as_view(), name="add_job"),
    # path("jobs/all/", views.AllClientsListView.as_view(), name="all_jobs"),
    path("clients/<int:pk>/", views.ClientView.as_view(), name="client"),
    path(
        "clients/<int:pk>/add_job/",
        views.JobCreateView.as_view(),
        name="add_job_client",
    ),
    path(
        "clients/<int:pk>/add_contact/",
        views.ContactCreateView.as_view(),
        name="add_contact",
    ),
    path(
        "clients/add/",
        views.ClientCreateView.as_view(),
        name="add_client",
    ),
    path(
        "jobs/<int:pk>/status/",
        views.JobChangeStatusView.as_view(),
        name="change_job_status",
    ),
    path(
        "jobs/<int:pk>/status/<int:status_pk>/",
        views.JobChangeStatusView.as_view(),
        name="edit_job_status",
    ),
]

ortoreal/ortoreal/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("select2/", include("django_select2.urls")),
    path("", include("inventory.urls", namespace="inventory")),
    path("", include("clients.urls", namespace="clients")),
    path("admin/", admin.site.urls),
]

ortoreal/inventory/models.py
import locale
from decimal import Decimal
from typing import Iterable, Optional

from django.contrib.auth import get_user_model
from django.db import models, transaction
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from clients.models import Job
from core.utils import get_date_display

User = get_user_model()


class Manufacturer(models.Model):
    name = models.CharField(max_length=1024, unique=True, blank=False, null=False)

    class Meta:
        verbose_name = "производитель"
        verbose_name_plural = "производители"

    def __str__(self):
        return f"{self.name}"


class Vendor(models.Model):
    name = models.CharField(max_length=1024, unique=True, blank=False, null=False)

    class Meta:
        verbose_name = "поставщик"
        verbose_name_plural = "поставщики"

    def __str__(self):
        return f"{self.name}"


class Order(models.Model):
    vendor = models.ForeignKey(
        Vendor, verbose_name="поставщик", on_delete=models.CASCADE, null=True
    )
    date = models.DateTimeField("дата", default=timezone.now, null=True)
    is_current = models.BooleanField("текущий", default=False)

    @classmethod
    def get_current(cls):
        order, _ = cls.objects.get_or_create(is_current=True, defaults={"date": None})
        return order

    class Meta:
        verbose_name = "заказ"
        verbose_name_plural = "заказы"

    def __str__(self) -> str:
        if self.is_current:
            return "текущий"
        date = get_date_display(self.date)
        return f"{self.vendor} ({date})"

    def save(self, *args, **kwargs):
        if not self.is_current:
            return super().save(*args, **kwargs)
        with transaction.atomic():
            Order.objects.filter(is_current=True).update(is_current=False)
            self.date = timezone.now()
            super().save(*args, **kwargs)

    def get_absolute_url(self):
        url = reverse("inventory:order_by_id", kwargs={"pk": self.pk})
        if self.is_current:
            url = reverse("inventory:order")
        return url


class Invoice(models.Model):
    number = models.CharField("номер", max_length=100, unique=True)
    order = models.ForeignKey(Order, verbose_name="заказ", on_delete=models.CASCADE)
    date = models.DateTimeField("дата", default=timezone.now)

    class Meta:
        verbose_name = "счёт"
        verbose_name = "счета"

    def __str__(self) -> str:
        return f"{self.number} {self.order.vendor}"


class Part(models.Model):
    vendor_code = models.CharField("артикул", max_length=256, unique=True)
    name = models.CharField("наименование", max_length=1024)
    units = models.CharField("единицы", max_length=100, blank=True, null=True)
    price = models.DecimalField(
        "цена, руб.", max_digits=11, decimal_places=2, blank=True, null=True
    )
    manufacturer = models.ForeignKey(
        Manufacturer,
        verbose_name="производитель",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )
    vendor = models.ForeignKey(
        Vendor,
        verbose_name="поставщик",
        on_delete=models.CASCADE,
        null=True,
        limit_choices_to=~models.Q(name="2"),
    )
    note = models.CharField("примечание", max_length=1024, blank=True, null=True)
    minimum_remainder = models.SmallIntegerField(
        "неснижаемый остаток",
        default=0,
    )

    @property
    def quantity_total(self):
        """
        Кол-во комплектующих, которые
        пришли на склад, и не взяты в работу.
        """
        total = self.items.filter(job=None, arrived=True).count()
        return f"{total}"

    quantity_total.fget.short_description = "кол-во"

    @classmethod
    def get_field_names(cls):
        return [f.verbose_name for f in cls._meta.fields if f.name != "units"]

    class Meta:
        verbose_name = "модель комплектующей"
        verbose_name_plural = "номенклатура"

    def __str__(self) -> str:
        return f"{self.vendor_code} - {self.name}"

    def get_absolute_url(self):
        return reverse("inventory:items", kwargs={"pk": self.pk})


class Item(models.Model):
    """
    Модель комплектующей.
    """

    part = models.ForeignKey(
        Part,
        verbose_name="Артикул",
        on_delete=models.CASCADE,
        related_name="items",
        blank=False,
        null=False,
    )
    date = models.DateTimeField("Дата", default=timezone.now)
    arrived = models.BooleanField("Пришло", default=False)
    vendor2 = models.BooleanField("Поставщик 2", default=False)
    job = models.ForeignKey(
        Job,
        verbose_name="Работа",
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name="items",
    )
    reserved = models.ForeignKey(
        Job,
        verbose_name="Резерв",
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name="reserved_items",
    )
    order = models.ForeignKey(
        Order,
        verbose_name="заказ",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name="items",
        default=Order.get_current,
    )
    invoice = models.ForeignKey(
        Invoice,
        verbose_name="счёт",
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name="items",
    )
    price = models.DecimalField(
        "цена, руб.", max_digits=11, decimal_places=2, default=Decimal("0.00")
    )
    free_order = models.BooleanField(
        "Свободный заказ",
        default=False,
        help_text="Запретить удаление из заказа при пересчёте резервов.",
    )

    @property
    def in_warehouse(self):
        if not self.arrived:
            return False
        if self.job is not None:
            return False
        return True

    @classmethod
    def get_field_names(cls):
        return [f.verbose_name for f in cls._meta.fields]

    class Meta:
        verbose_name = "комплектующая"
        verbose_name_plural = "комплектующие"

    def __str__(self):
        return str(self.part.vendor_code)

    def get_absolute_url(self):
        return reverse(
            f"admin:{self._meta.app_label}_{self._meta.model_name}_change",
            kwargs={"object_id": self.id},
        )


class ProsthetistItem(models.Model):
    prosthetist = models.ForeignKey(
        User,
        verbose_name="протезист",
        limit_choices_to={"is_prosthetist": True},
        on_delete=models.CASCADE,
        related_name="items",
    )
    item = models.ForeignKey(
        Item,
        verbose_name="комплектующая",
        on_delete=models.CASCADE,
        related_name="prosthetist",
    )
    date = models.DateTimeField("дата", default=timezone.now)

    class Meta:
        verbose_name = "инвентарь у протезиста"
        verbose_name_plural = "инвентарь у протезиста"

    def __str__(self) -> str:
        date = timezone.localtime(self.date).strftime("%d-%b-%Y %H:%M")
        return f"({date}) {self.item.part}"


class Prosthesis(models.Model):
    class Region(models.TextChoices):
        MOSCOW = "Moscow", _("Москва")
        MOSCOW_REGION = "Moscow region", _("Московская область")

    class ProsthesisType(models.TextChoices):
        T1 = 1, "тип 1"
        T2 = 2, "тип 2"
        T3 = 3, "тип 3"
        T4 = 4, "тип 4"

    number = models.CharField("артикул", max_length=512, unique=True)
    kind = models.CharField(
        "тип", max_length=1024, blank=True, choices=ProsthesisType.choices
    )
    # name = models.CharField("наименование", max_length=1024, blank=True)
    price = models.DecimalField("стоимость", max_digits=11, decimal_places=2)
    region = models.CharField("регион", max_length=128, choices=Region.choices)
    price_start_date = models.DateField(
        "Начало действия цены",
        blank=False,
        null=True,
    )
    price_end_date = models.DateField(
        "Конец действия цены",
        blank=False,
        null=True,
    )
    is_active = models.BooleanField("активный", default=True, blank=True, null=True)

    class Meta:
        verbose_name = "протез"
        verbose_name_plural = "протезы"

    def __str__(self) -> str:
        return f"{self.number}"


class InventoryLog(models.Model):
    class Operation(models.TextChoices):
        RECEPTION = "RECEPTION", _("Приход")
        RETURN = "RETURN", _("Возврат")
        TAKE = "TAKE", _("Расход")

    operation = models.CharField("операция", max_length=32, choices=Operation.choices)
    items = models.ManyToManyField(
        Item, verbose_name="комплектующие", related_name="logs"
    )
    job = models.ForeignKey(
        Job,
        verbose_name="работа",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )
    prosthetist = models.ForeignKey(
        User,
        verbose_name="протезист",
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
    )
    order = models.ForeignKey(
        Order,
        verbose_name="заказ",
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
    )
    invoice = models.ForeignKey(
        Invoice,
        verbose_name="счёт",
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
    )
    date = models.DateTimeField("дата", default=timezone.now)
    comment = models.CharField("комментарий", max_length=1024, blank=True)

    class Meta:
        verbose_name = "операция на складе"
        verbose_name_plural = "операции на складе"

    def __str__(self):
        return f"{self.operation}"

    def get_absolute_url(self):
        return reverse("inventory:log_items", kwargs={"pk": self.pk})

ortoreal/templates/includes/form_errors.html
{% if form.errors %}
  {% for field in form %}
    {% for error in field.errors %}            
      <div class="alert alert-danger">
        {{ error|escape }}
      </div>
    {% endfor %}
  {% endfor %}
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
      {{ error|escape }}
    </div>
  {% endfor %}
{% endif %}

ortoreal/templates/includes/form_fields.html
{% load user_filters %}
{% for field in form %}
  <div class="form-group col"
       {% if field.field.required %} aria-required="true"{% endif %}>
    {% if forloop.parentloop.first %}
      <label for="{{ field.id_for_label }}"
             {% if field.help_text %} title="{{ field.help_text|safe }}"{% endif %}>
        {{ field.label }}
        {% if field.field.required %}<span class="required text-danger">*</span>{% endif %}
      </label>
    {% endif %}
    {{ field|addclass:'form-control' }}
    {% comment %}
    {% if field.help_text %}
      <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
    {% endif %}
    {% endcomment %}
    {% for error in field.errors %}<div class="alert alert-danger p-0 text-center">{{ error|escape }}</div>{% endfor %}
  </div>
{% endfor %}

ortoreal/templates/includes/form_table_head.html
<thead class="text-center">
  <tr>
    {% for field in form.visible_fields %}
      <th scope="col"
          class="justify-content-center {% if field.name == 'part' %}fixed-width{% endif %}"
          {% if field.help_text %} title="{{ field.help_text|safe }}"{% endif %}>
        {{ field.label }}
        {% if field.field.required %}<span class="required text-danger">*</span>{% endif %}
      </th>
    {% endfor %}
  </tr>
</thead>

ortoreal/templates/includes/header.html
{% load static %}
<header>
  <link rel="stylesheet" href="{% static "css/header.css" %}" />
  <nav class="navbar navbar-expand-md navbar-light"
       style="background-color: lightgrey">
    <div class="container">
      <a class="navbar-brand d-flex flex-row" href="{% url 'clients:index' %}">
        <img src="{% static 'img/logo.png' %}"
             height="30"
             class="d-inline-block align-top"
             alt="">
        <div>
          <span style="color: green; line-height: 16px; display: block;">OРТО
            <br>
          РЕАЛ</span>
        </div>
      </a>
      <button class="navbar-toggler"
              type="button"
              data-bs-toggle="collapse"
              data-bs-target="#navbarNav"
              aria-controls="navbarNav"
              aria-expanded="false"
              aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      {% with view_name=request.resolver_match.view_name %}
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="nav nav-pills ms-auto">
            {% if user.is_staff or user.is_manager %}
              <li class="nav-item">
                <a class="btn btn-outline-info me-1" href="{% url 'admin:index' %}">Админка</a>
              </li>
            {% endif %}
            <li class="nav-item">
              <a class="nav-link{% if view_name == 'clients:clients' %} active{% endif %}"
                 href="{% url 'clients:clients' %}">Клиенты</a>
            </li>
            <li class="nav-item">
              <a class="nav-link{% if view_name == 'inventory:nomenclature' %} active{% endif %}"
                 href="{% url 'inventory:nomenclature' %}">Склад</a>
            </li>
            <li class="nav-item">
              <a class="nav-link{% if view_name == 'inventory:prosthesis_list' %} active{% endif %}"
                 href="{% url 'inventory:prosthesis_list' %}">Протезы</a>
            </li>
            <li class="nav-item">
              <a class="nav-link{% if view_name == 'inventory:margins' %} active{% endif %}"
                 href="{% url 'inventory:margins' %}">Маржа</a>
            </li>
            <li class="nav-item">
              <a class="nav-link{% if view_name == 'inventory:orders' or view_name == 'inventory:order' or view_name == 'inventory:order_by_id' %} active{% endif %}"
                 href="{% url 'inventory:orders' %}">Заказы</a>
            </li>
            <li class="nav-item">
              <a class="nav-link{% if view_name == 'inventory:prosthetist_items' %} active{% endif %}"
                 href="{% url 'inventory:prosthetist_items' %}">Инвентарь у протезистов</a>
            </li>
            {% comment %}
            <li class="nav-item">
              <a class="nav-link{% if view_name == 'clients:contacts' %} active{% endif %}" href="{% url 'clients:contacts' %}">
                Обращения
              </a>
            </li>
            {% endcomment %}
            <li class="nav-item">
              <a class="nav-link{% if view_name == 'inventory:reception' or view_name == 'inventory:reception_invoice' %} active{% endif %}"
                 href="{% url 'inventory:reception' %}">Приход</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-wrap{% if view_name == 'inventory:logs' %} active{% endif %}"
                 href="{% url 'inventory:logs' %}">Операции</a>
            </li>
            {% if user.is_manager or user.is_prosthetist %}
              <li class="nav-item">
                <a class="nav-link text-wrap{% if view_name == 'inventory:all_job_sets' or view_name == 'inventory:job_sets' %} active{% endif %}"
                   {% if user.is_manager %}
                   href="{% url 'inventory:all_job_sets' %}">
                {% elif user.is_prosthetist %}
                  href="{% url 'inventory:job_sets' %}">
                {% endif %}
                Комплектующие
              </a>
            </li>
          {% endif %}
          {% if user.is_prosthetist or user.is_manager %}
            <li class="nav-item">
              <div class="btn-group" role="group">
                <a class="btn btn-warning{% if view_name == 'inventory:take_items' %} active{% endif %}"
                   href="{% url 'inventory:take_items' %}">Взять</a>
                <a class="btn btn-danger{% if view_name == 'inventory:return_items' %} active{% endif %}"
                   href="{% url 'inventory:return_items' %}">Вернуть</a>
              </div>
            </li>
          {% endif %}
          {% if user.is_authenticated %}
            {% comment %}
            <li class="nav-item"> 
              <a class="nav-link {% if view_name == 'posts:post_create' %}active{% endif %}" href="{% url 'posts:post_create' %}">
                Новая запись
              </a>
            </li>
            {% endcomment %}
            <li class="nav-item">
              <a class="nav-link disabled">{{ user }}</a>
              {% comment %}
              <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <li>
                  <a class="dropdown-item" href="{% url 'posts:profile' user.username %}">Профиль</a>
                </li>
                <li><hr class="dropdown-divider"></li>
                <li>
                  <a class="dropdown-item" href="{% url 'users:password_change' %}">Изменить пароль</a>
                </li>
                <li>
                  <a class="dropdown-item" href="{% url 'users:logout' %}">Выйти</a>
                </li>
              </ul>
              {% endcomment %}
            </li>
            {% comment %}
          {% else %}
            <li class="nav-item"> 
              <a class="nav-link {% if view_name == 'users:login' %} active bg-secondary link {% else %} link-dark {% endif %}" href="{% url 'users:login' %}">
                Войти
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if view_name == 'users:signup' %} active bg-secondary link {% else %} link-dark {% endif %}" href="{% url 'users:signup' %}">
                Регистрация
              </a>
            </li>
            {% endcomment %}
          {% endif %}
        </ul>
      </div>
    {% endwith %}
  </div>
</nav>
</header>

ortoreal/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
  <nav class="my-5" aria-label="Page navigation">
    <ul class="pagination justify-content-center">
      {% comment %}
      {% if page_obj.number|add:"-2" > 0 %}
        <li class="page-item">
          <a class="page-link" href="?page=1"><<</a>
        </li>
      {% endif %}
      {% endcomment %}
      {% if page_obj.number|add:"-5" > 1 %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}"><</a>
        </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% elif i == 1 or i == page_obj.paginator.num_pages or i > page_obj.number|add:"-5" and i < page_obj.number|add:"5" %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% elif i == page_obj.number|add:"-5" or i == page_obj.number|add:"5" %}
          <li class="page-item">
            <span class="page-link">. . .</span>
          </li>
        {% endif %}
      {% endfor %}
      {% if page_obj.paginator.num_pages > page_obj.number|add:"5" %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">></a>
        </li>
      {% endif %}
      {% comment %}
      {% if page_obj.paginator.num_pages > page_obj.number|add:"4" %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">>></a>
        </li>
      {% endif %}
      {% endcomment %}
    </ul>
  </nav>
{% endif %}

ortoreal/templates/includes/table_head.html
<thead class="text-center">
  <tr>
    {% for field in table_head %}<th scope="col" class="justify-content-center">{{ field }}</th>{% endfor %}
  </tr>
</thead>